### ISSUE TITLE
input type

### ISSUE THREAD

**Issue by wuwo007** [pcdslab/MSREDUCE#2]
Good work!

I am confused that what type of mass spectrum does MS-Reduce support? Does it support .mgf files?

**Comment by Usman095** [comment]
Hi @wuwo007 

MS-Reduce only supports .ms2 file types. You can use [msconvert ](https://proteowizard.sourceforge.io/download.html) to convert .mgf files to .ms2.

Hope this helps.

**Comment by wuwo007** [comment]
OK.  Thanks
